-- create database
CREATE DATABASE NewYork_Crime_Complaints;
use NewYork_Crime_Complaints;

-- drop any existing tables
drop table if exists populationAt;
drop table if exists locationAt;
drop table if exists occursAt;
drop table if exists Has;
drop table if exists EndDateTime;
drop table if exists StartDateTime;
drop table if exists InternalClassification;
drop table if exists Crime;
drop table if exists Complaint;
drop table if exists CrimeLocation;
drop table if exists PopByBoro;
drop table if exists NYCCoords;
drop table if exists GlobalCoords;

-- create tables
CREATE TABLE Crime (
    KY_CD int NOT NULL,
    OFNS_DESC varchar(50) NOT NULL,
    CRM_ATPT_CPTD_CD varchar(20) NOT NULL,
    LAW_CAT_CD varchar(20) NOT NULL,
    CONSTRAINT PK_Crime PRIMARY KEY (KY_CD,CRM_ATPT_CPTD_CD)
);

CREATE TABLE Coordinate (
    Longitude int NOT NULL,
    Latitude int NOT NULL,
    Floor_num int NOT NULL,
    CONSTRAINT PK_StartDateTime PRIMARY KEY (Longitude, Latitude, Floor_num)
);

CREATE TABLE occured_at (
    
)

CREATE TABLE Complaint (
    CMPLNT_NUM int NOT NULL,
    RPT_DT varchar(11) NOT NULL,
    JURIS_DESC varchar(50) NOT NULL,
    PRIMARY KEY (CMPLNT_NUM)
);

CREATE TABLE StartDateTime (
    CMPLNT_NUM int NOT NULL,
    CMPLNT_FR_DT varchar(11) NOT NULL,
    CMPLNT_FR_TM varchar(11) NOT NULL,
    CONSTRAINT PK_StartDateTime PRIMARY KEY (CMPLNT_FR_DT,CMPLNT_FR_TM),
    FOREIGN KEY (CMPLNT_NUM) REFERENCES Complaint(CMPLNT_NUM)
);

CREATE TABLE EndDateTime (
    CMPLNT_NUM int NOT NULL,
    CMPLNT_FR_DT varchar(11) NOT NULL,
    CMPLNT_FR_TM varchar(11) NOT NULL,
    CMPLNT_TO_DT varchar(11) NOT NULL,
    CMPLNT_TO_TM varchar(11) NOT NULL,
    CONSTRAINT PK_EndDateTime PRIMARY KEY (CMPLNT_TO_DT,CMPLNT_TO_TM),
    FOREIGN KEY (CMPLNT_NUM) REFERENCES Complaint(CMPLNT_NUM),
    FOREIGN KEY (CMPLNT_FR_DT, CMPLNT_FR_TM) REFERENCES StartDateTime(CMPLNT_FR_DT, CMPLNT_FR_TM)
);

CREATE TABLE InternalClassification (
    PD_CD int NOT NULL,
    PD_DESC varchar(100), 
    PRIMARY KEY (PD_CD)
);

CREATE TABLE PopByBoro (
    Borough varchar(13) NOT NULL,
    YR_1950 varchar(12) NOT NULL,
    1950_BORO_SHARE varchar(10) NOT NULL,
    YR_1960 varchar(12) NOT NULL,
    1960_BORO_SHARE varchar(10) NOT NULL,
    YR_1970 varchar(12) NOT NULL,
    1970_BORO_SHARE varchar(10) NOT NULL,
    YR_1980 varchar(12) NOT NULL,
    1980_BORO_SHARE varchar(10) NOT NULL,   
    YR_1990 varchar(12) NOT NULL,
    1990_BORO_SHARE varchar(10) NOT NULL,
    YR_2000 varchar(12) NOT NULL,
    2000_BORO_SHARE varchar(10) NOT NULL,
    YR_2010 varchar(12) NOT NULL,
    2010_BORO_SHARE varchar(10) NOT NULL,    
    YR_2020 varchar(12) NOT NULL,
    2020_BORO_SHARE varchar(10) NOT NULL,
    YR_2030 varchar(12) NOT NULL,
    2030_BORO_SHARE varchar(10) NOT NULL,
    YR_2040 varchar(12) NOT NULL,
    2040_BORO_SHARE varchar(10) NOT NULL,
    PRIMARY KEY (Borough)
);

CREATE TABLE CrimeLocation (
    ADDR_PCT_CD int NOT NULL,
    LOC_OF_OCCUR_DESC varchar(30) NOT NULL, 
    PREM_TYP_DESC varchar(50) NOT NULL,
    PARKS_NM varchar(100), -- optional
    HADEVELOPT varchar(100), -- optional 
    BORO_NM varchar(13) NOT NULL,
    CONSTRAINT PK_EndDateTime PRIMARY KEY (ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC)
);

CREATE TABLE GlobalCoords (
    LATITUDE varchar(12) NOT NULL,
    LONGITUDE varchar(12) NOT NULL,
    CONSTRAINT PK_GlobalCoords PRIMARY KEY (LATITUDE,LONGITUDE)
);

CREATE TABLE NYCCoords (
    X_COORD_CD int NOT NULL,
    Y_COORD_CD int NOT NULL,
    CONSTRAINT PK_NYCCoords PRIMARY KEY (X_COORD_CD,Y_COORD_CD)
);

CREATE TABLE populationAt (
    ADDR_PCT_CD int NOT NULL,
    LOC_OF_OCCUR_DESC varchar(30) NOT NULL,
    PREM_TYP_DESC varchar(50) NOT NULL,
    BORO_NM varchar(13) NOT NULL,
    CONSTRAINT PK_populationAt PRIMARY KEY (BORO_NM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC),
    FOREIGN KEY (ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC) REFERENCES CrimeLocation(ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC) ON UPDATE CASCADE,
    FOREIGN KEY (BORO_NM) REFERENCES PopByBoro(Borough)
);

CREATE TABLE locationAt (
    ADDR_PCT_CD int NOT NULL,
    LOC_OF_OCCUR_DESC varchar(30) NOT NULL,
    PREM_TYP_DESC varchar(50) NOT NULL,
    X_COORD_CD int NOT NULL,
    Y_COORD_CD int NOT NULL,
    LATITUDE varchar(12) NOT NULL,
    LONGITUDE varchar(12) NOT NULL,
    CONSTRAINT PK_locationAt PRIMARY KEY (ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC, X_COORD_CD, Y_COORD_CD, LATITUDE, LONGITUDE),
    FOREIGN KEY (LATITUDE, LONGITUDE) REFERENCES GlobalCoords(LATITUDE, LONGITUDE),
    FOREIGN KEY (X_COORD_CD, Y_COORD_CD) REFERENCES NYCCoords(X_COORD_CD, Y_COORD_CD),
    FOREIGN KEY (ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC) REFERENCES CrimeLocation(ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC) ON UPDATE CASCADE
);

CREATE TABLE occursAt (
    CMPLNT_NUM int NOT NULL,
    ADDR_PCT_CD int NOT NULL,
    LOC_OF_OCCUR_DESC varchar(30) NOT NULL,
    PREM_TYP_DESC varchar(50) NOT NULL,
    CONSTRAINT PK_occursAt PRIMARY KEY (CMPLNT_NUM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC),
    FOREIGN KEY (ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC) REFERENCES CrimeLocation(ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC) ON UPDATE CASCADE
);

CREATE TABLE Has (
    CMPLNT_NUM int NOT NULL,
    KY_CD int NOT NULL,
    CRM_ATPT_CPTD_CD varchar(20) NOT NULL,
    PD_CD int NOT NULL,
    CONSTRAINT PK_HAS PRIMARY KEY (CMPLNT_NUM, KY_CD, CRM_ATPT_CPTD_CD, PD_CD),
    FOREIGN KEY (CMPLNT_NUM) REFERENCES Complaint(CMPLNT_NUM),
    FOREIGN KEY (KY_CD, CRM_ATPT_CPTD_CD) REFERENCES Crime(KY_CD, CRM_ATPT_CPTD_CD),
    FOREIGN KEY (PD_CD) REFERENCES InternalClassification(PD_CD)
);

-- load data from csv files
LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE Crime 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (@CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    KY_CD, OFNS_DESC, @PD_CD, @PD_DESC, CRM_ATPT_CPTD_CD, LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE Complaint 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);


LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE StartDateTime 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (CMPLNT_NUM, CMPLNT_FR_DT, CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE EndDateTime 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (CMPLNT_NUM, CMPLNT_FR_DT, CMPLNT_FR_TM, CMPLNT_TO_DT, CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE InternalClassification 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (@CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, PD_CD, PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'Population_by_Borough_NYC.csv' INTO TABLE PopByBoro 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE CrimeLocation 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (@CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    BORO_NM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC, PARKS_NM, HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE GlobalCoords 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (@CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, Latitude, Longitude, @Lat_Lon);
    
LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE NYCCoords 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (@CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    X_COORD_CD, Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE populationAt 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (@CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    BORO_NM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE locationAt 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (@CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    X_COORD_CD, Y_COORD_CD, Latitude, Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE occursAt 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    @KY_CD, @OFNS_DESC, @PD_CD, @PD_DESC, @CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

LOAD DATA LOCAL INFILE 'NYPD_Complaint_Data_Historic.csv' INTO TABLE Has 
    FIELDS TERMINATED by ','
    ENCLOSED by '"'
    LINES TERMINATED by '\n'
    IGNORE 1 LINES
    (CMPLNT_NUM, @CMPLNT_FR_DT, @CMPLNT_FR_TM, @CMPLNT_TO_DT, @CMPLNT_TO_TM, @RPT_DT,
    KY_CD, @OFNS_DESC, PD_CD, @PD_DESC, CRM_ATPT_CPTD_CD, @LAW_CAT_CD, @JURIS_DESC,
    @BORO_NM, @ADDR_PCT_CD, @LOC_OF_OCCUR_DESC, @PREM_TYP_DESC, @PARKS_NM, @HADEVELOPT,
    @X_COORD_CD, @Y_COORD_CD, @Latitude, @Longitude, @Lat_Lon);

-- create indexes    
CREATE INDEX CMPLNT_NUM ON Complaint(CMPLNT_NUM);
CREATE INDEX KY_CD ON Crime(KY_CD);
CREATE INDEX ADDR_PCT_CD ON CrimeLocation(ADDR_PCT_CD);

CREATE INDEX X_COORD_CD ON NYCCoords(X_COORD_CD);
CREATE INDEX Y_COORD_CD ON NYCCoords(Y_COORD_CD);   

CREATE INDEX LATITUDE ON GlobalCoords(LATITUDE);
CREATE INDEX LONGITUDE ON GlobalCoords(LONGITUDE);